### ISSUE TITLE
NDArray string problem

### ISSUE THREAD

**Issue by lokinfey** [SciSharp/NumSharp#341]
I try to use
 var bb8List =  new NDArray(typeof(string) , new Shape(bb8Num));

but it show error like this 

Exception has occurred: CLR/System.NotSupportedException
An unhandled exception of type 'System.NotSupportedException' occurred in NumSharp.Core.dll: 'Specified method is not supported.'
   at NumSharp.Backends.Unmanaged.ArraySlice.Allocate(Type elementType, Int32 count, Boolean fillDefault)
   at NumSharp.Backends.UnmanagedStorage.Allocate(Shape shape, Type dtype, Boolean fillZeros)
   at NumSharp.NDArray..ctor(Type dtype, Shape shape)
   at TFDemo.Program.Main(String[] args) in /Users/lokinfey/Desktop/File/Proj/AI/tensorflownet/code/TFDemo/Program.cs:line 61

**Comment by Nucs** [comment]
We currently do not support NDArray of string because `System.String` is not an unmanaged object.
We do plan to implement it ASAP as ML.NET team needs it too.
