### ISSUE TITLE
np.save throws Exception on large datasets

### ISSUE THREAD

**Issue by pavlexander** [SciSharp/NumSharp#409]
I am trying to save the 3D array of doubles of size `{double[719118, 61, 7]}`
![image](https://user-images.githubusercontent.com/20644772/80531339-23b59a00-89a3-11ea-8343-c8f0acaf3dcf.png)

Since it's a 64 bit application and I have plenty on RAM - I can operate with arrays of such size OK. But the numpy throws following error when saving to file:

> System.OverflowException: 'Arithmetic operation resulted in an overflow.'

![image](https://user-images.githubusercontent.com/20644772/80531516-74c58e00-89a3-11ea-9178-e89d4b3b3e45.png)

> System.OverflowException
>   HResult=0x80131516
>   Message=Arithmetic operation resulted in an overflow.
>   Source=NumSharp.Core
>   StackTrace:
>    at NumSharp.np.writeValueMatrix(BinaryWriter reader, Array matrix, Int32 bytes, Int32[] shape)
>    at NumSharp.np.Save(Array array, Stream stream)
>    at NumSharp.np.Save(Array array, String path)
>    at NumSharp.np.save(String filepath, Array arr)
>    at Processor.DataPersister.SaveArrayAsNumpyArray(String filePath, String fileName, Array numpyArray) in C:\Users\Lucky\source\repos\ChromedriverPlot\Processor\DataPersister.cs:line 55
>    at Processor.DataPersister.PreproccessExtractedSymbols(DateTime dt, String symbolName, Int32 stepMinutePeriod) in C:\Users\Lucky\source\repos\ChromedriverPlot\Processor\DataPersister.cs:line 523
>    at Processor.DataPersister.<>c__DisplayClass9_0.<PreproccessExtractedSymbolsWrapper>b__0(String symbolName) in C:\Users\Lucky\source\repos\ChromedriverPlot\Processor\DataPersister.cs:line 454
>    at System.Threading.Tasks.Parallel.<>c__DisplayClass33_0`2.<ForEachWorker>b__0(Int32 i)
>    at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
> 

Is there a way to bypass/fix this issue?

It seems like `numpy` has no problems converting standard 3D array into `numpy` array.. but saving it is impossible.. so both save method overloads throw an exception.

`NumSharp 0.20.5`
`.Net Core 3.1` x64 app
`win 10 x64`
`VS 2019`

**Comment by pavlexander** [comment]
the issue is related to the fact that byte array cannot hold more than 
`int byteMaxSize = 2_147_483_591;`
number of elements in it.. (tested on framework 4.7.2), so the following line fails:

```
            var buffer = new byte[bytes * total]; // here
            Buffer.BlockCopy(matrix, 0, buffer, 0, buffer.Length);
            reader.Write(buffer, 0, buffer.Length);
```

if you want to fix it - you need to write a logic that would write the data in **chunks**, in cases when the `bytes * total` value exceeds the maximum allowed number of elements in byte array..

There might be other places that require a fix, I haven't checked..
