### ISSUE TITLE
0.3.0 from NuGet throwing NotSupportedException on negate function call

### ISSUE THREAD

**Issue by gandalfh** [SciSharp/NumSharp#443]
This code behaves as expected on version 0.20.5 from NuGet (https://www.nuget.org/packages/NumSharp/)
`
var ones = np.ones((10, 1));
ones.negate();
`
But after upgrading to 0.3.0 a NotSupportedException is thrown:

   at NumSharp.Backends.DefaultEngine.Negate(NDArray& nd)
   at NumSharp.NDArray.negate()

**Comment by Nucs** [comment]
Related to #447

**Comment by Nucs** [comment]
This has been fixed. The `negate()` method now works correctly:

```csharp
var ones = np.ones((10, 1));
ones.negate();  // Works
```

Resolved via #600, #602, #603, #596.
