### ISSUE TITLE
[Bug] np.random.choice raise Exception

### ISSUE THREAD

**Issue by QingtaoLi1** [SciSharp/NumSharp#466]
As shown in src/NumSharp.Core/RandomSampling/np.random.choice.cs, the function accepts `probabilities` as `double[]`, but in line #43 it is directly passed to `np.cumsum` which does NOT accept `double[]` as input. The result is that an Exception is raised with message "Specified method is not supported." and the stack trace is:
`   at NumSharp.NPTypeCodeExtensions.GetAccumulatingType(NPTypeCode typeCode)
   at NumSharp.Backends.DefaultEngine.cumsum_elementwise(NDArray& arr, Nullable`1 typeCode)
   at NumSharp.Backends.DefaultEngine.ReduceCumAdd(NDArray& arr, Nullable`1 axis_, Nullable`1 typeCode)
   at NumSharp.np.cumsum(NDArray arr, Nullable`1 axis, Nullable`1 typeCode)`.

**Comment by QingtaoLi1** [comment]
It seems there is no UT for this function in this repo.

**Comment by QingtaoLi1** [comment]
Besides, another argument `replace` is not used at all in both overrides.

**Comment by QingtaoLi1** [comment]
I do a simple test on `np.cumsum` since it is in the stack trace:
`        public static void RandomChoice()
        {
            var array = np.arange(1, 50265);
            var arrayDouble = 1.0 / array.astype(np.@double);
            var cumsum = np.cumsum(arrayDouble, typeCode: arrayDouble.typecode);  // OK
            var cumsum2 = np.cumsum(arrayDouble);                                                      // raise Exception mentioned above
        }
`

It looks like there's something wrong in the default typeCode. BTW, I'm using the latest NumSharp 0.30.0 version.

**Comment by UCtreespring** [comment]
相同的问题，你解决了吗？

**Comment by QingtaoLi1** [comment]
目前发现的解决方案就是上面那样自己copy一个，加上typeCode就能跑了

**Comment by UCtreespring** [comment]
是我没有留意到那个“Ok”的注释，按照你的方案，我复制了官方Numsharp-master中的相关方法，添加了相关的typeCode参数，问题解决。非常感谢！

**Comment by Nucs** [comment]
This has been fixed. `np.random.choice` now works correctly:

```csharp
np.random.seed(42);
var result = np.random.choice(5, 3, true);
// Result: [3, 4, 2]
```

The underlying `cumsum` issue that caused the NotSupportedException has been resolved.

Resolved via #600, #602, #603, #596.
