### ISSUE TITLE
Unhandled Exception: System.NotSupportedException: Specified method is not supported.

### ISSUE THREAD

**Issue by Kanglatae** [SciSharp/NumSharp#471]
**I am getting an error at this line of code:** 
 `double theta3_2 = Math.Atan2(a3, d4) - Math.Atan2(K / p3, -np.sqrt(np.power(1 - (K / p3), 2)));`

Unhandled Exception: System.NotSupportedException: Specified method is not supported.
   at NumSharp.Backends.DefaultEngine.Negate(NDArray& nd) in D:\SciSharp\NumSharp\src\NumSharp.Core\Backends\Default\Math\Default.Negate.cs:line 119
   at NumSharp.NDArray.op_UnaryNegation(NDArray x) in D:\SciSharp\NumSharp\src\NumSharp.Core\Operations\Elementwise\NDArray.Primitive.cs:line 10
   at Robotics.InverseNP.Main(String[] args) in C:\Users\..........................

**Comment by Nucs** [comment]
This has been fixed. Unary negation now works correctly:

```csharp
var arr = np.sqrt(np.array(new[] { 4.0, 9.0, 16.0 }));
var negated = -arr;
// Result: [-2, -3, -4]
```

Resolved via #600, #602, #603, #596.
