### ISSUE TITLE
np.random.choice raised  System.NotSupportedException

### ISSUE THREAD

**Issue by alvinfebriando** [SciSharp/NumSharp#488]
error on np.random.choice, it said "Specified method isn not supported". Is my usage wrong?

```csharp
var score = np.arange(1,6);
var p = new[] { 0.2, 0.2, 0.2, 0.2, 0.2 };
var result = np.random.choice(score, probabilities: p);
```

Stack trace
```
Unhandled exception. System.NotSupportedException: Specified method is not supported.
   at NumSharp.NPTypeCodeExtensions.GetAccumulatingType(NPTypeCode typeCode)
   at NumSharp.Backends.DefaultEngine.cumsum_elementwise(NDArray& arr, Nullable`1 typeCode)
   at NumSharp.Backends.DefaultEngine.ReduceCumAdd(NDArray& arr, Nullable`1 axis_, Nullable`1 typeCode)
   at NumSharp.np.cumsum(NDArray arr, Nullable`1 axis, Nullable`1 typeCode)
   at NumSharp.NumPyRandom.choice(Int32 a, Shape shape, Boolean replace, Double[] probabilities)
   at NumSharp.NumPyRandom.choice(NDArray arr, Shape shape, Boolean replace, Double[] probabilities)
   at Program.<Main>$(String[] args) 
```

**Comment by bojake** [comment]
I created a test case with your exact code and ran it using my dev fork of NumSharp. No errors were produced. Are you using an out dated NumSharp?

**Comment by Nucs** [comment]
This has been fixed. `np.random.choice` now works:

```csharp
np.random.seed(42);
var result = np.random.choice(5, 3, true);  // Works: [3, 4, 2]
```

Resolved via #600, #602, #603, #596.
